### ISSUE TITLE
データベース設計

### ISSUE THREAD

**Issue by nyamadori** [nyamadori/rails-weblog#1]
## 命名規則

テーブル名や属性名の規則は基本的に Rails の規則を踏襲する。
## DB の使い分け
- MySQL ではリレーショナルなデータやメタデータを管理する
- 実データ (記事のタイトルや本文) は MongoDB で管理する
## MySQL

MySQL から MongoDB のデータを参照するための属性の名前には `_oid` を末尾に付与する。
### articles テーブル

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| int | id | 記事を一意に特定する ID |
| string | title_oid | タイトル本体を特定する MongoDB の ObjectID |
| string | body_oid | 記事本文を特定する MongoDB の ObjectID |
| int | category_id | 所属カテゴリを特定するための categories テーブルへの ID |
| datetime | published_at | 投稿日時 |
### categories テーブル

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| int | id | カテゴリを一意に特定する ID |
| string | name | カテゴリ名 |
### titles コレクション

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| ObjectID | _id | タイトルを一意に特定する ID |
| string | body | タイトル本体文字列 |
### bodies コレクション

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| ObjectID | _id | 本文を一意に特定する ID |
| string | body | 本文本体文字列 |

**Comment by hashimoto-speee** [comment]
MongoDBはRDBと違い、テーブル、カラムというデータ構成ではないので
title,bodiesは分けなくても大丈夫です。
contentsという一つのコレクション（テーブル）にして保存しましょう！

ObjectId
int type（タイトル：記事）
string 本文

Mysql側でタイトルと記事が特定できるのでMongoには一つのコレクションで大丈夫です

**Comment by nyamadori** [comment]
@hashimoto-speee 承知しました

MySQLのテーブルは最初の投稿のとおりで行きます。
MongoDBは以下のとおりにします。

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| ObjectID | _id | コンテンツを一意に特定する ID |
| int | type | コンテンツの種類 |
| string | body | コンテンツ文字列 |

**Comment by nyamadori** [comment]
@hashimoto-speee 

ただ疑問に思うのは MongoDB のドキュメントを作成するタイミングです。
ActiveRecord の before_save で Mongo のドキュメントを作成 / 変更する実装ですか?

**Comment by hashimoto-speee** [comment]
もちろん複数のストレージに書き込むためトランザクションを意識する必要があります。
たとえばMysqlは書き込めたが、Mongoが落ちていたら
Mysqlのデータはロールバックが必要ですね。
いろいろ試してみましょう！

**Comment by hashimoto-speee** [comment]
@nyamadori 
といいつつもMongoに書き込みする必要なアプリを今回作る必要性は低いので
トランザクションは気にしなくても大丈夫です。（ただ本番サービスなどでは必要）
なのでbefore_saveでmongoidのModel呼び出しでおｋです

**Comment by nyamadori** [comment]
@hashimoto-speee 分かりました!
本番サービスでは確かにロールバックが必要ですね。
ひとまず、ActiveRecord の before_save で Mongo のドキュメントを作成 / 変更を行うように実装することにします!
ありがとうございます。

**Comment by nyamadori** [comment]
# 確定版

## 命名規則

テーブル名や属性名の規則は基本的に Rails の規則を踏襲する。

## DB の使い分け
- MySQL ではリレーショナルなデータやメタデータを管理する
- 実データ (記事のタイトルや本文) は MongoDB で管理する

## MySQL

MySQL から MongoDB のデータを参照するための属性の名前には `_oid` を末尾に付与する。

### articles テーブル

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| int | id | 記事を一意に特定する ID |
| string | title_oid | タイトル本体を特定する MongoDB の ObjectID |
| string | body_oid | 記事本文を特定する MongoDB の ObjectID |
| int | category_id | 所属カテゴリを特定するための categories テーブルへの ID |
| datetime | published_at | 投稿日時 |

### categories テーブル

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| int | id | カテゴリを一意に特定する ID |
| string | name | カテゴリ名 |

## MongoDB

### contents コレクション

| 型 | 属性名 | 役割 |
| --- | --- | --- |
| ObjectID | _id | コンテンツを一意に特定する ID |
| int | type | コンテンツの種類 |
| string | body | コンテンツ文字列 |
