### ISSUE TITLE
【リファクタ】modelのリファクタ

### ISSUE THREAD

**Issue by hashimoto-speee** [nyamadori/rails-weblog#15]
mongoの取り扱いをActiveRecode準拠にする

**Comment by nyamadori** [comment]
@hashimoto-speee 

`after_find` コールバックで `find` メソッド呼び出した後に `fetch_mongo` と同等の処理を行えば、`fetch_mongo` メソッドをインスタンス経由で呼ぶ必要がなくなります。
`find` した後に `fetch_mongo` を呼ぶようなダサいコードが消えてすっきりします。

しかし、パフォーマンス的に大丈夫かどうか分からなかったので、`fetch_mongo` を別に呼ぶ形をとっています。
パフォーマンスの観点から上のやり方はイケてますかね?

**Comment by hashimoto-speee** [comment]
@nyamadori 
RailsならRails準拠で書きましょう。
パフォーマンスはチューニング領域、またはレビュー時に確認で良いかと思います！
PRにここパフォーマンス的にどう？とか書けばレビューアーも注意してみますよ。

articleというモデルにcontentが含まれるのであればController側で
article = Article.find(params[:id])
article.fetch_mongo
上記のように書かないようにするほうが良いと思います！
この内容ならパフォーマンス的にはどちらも差が出にくいですね

ControllerもModelもすっきりするのであればそちらが良いです。

**Comment by nyamadori** [comment]
@hashimoto-speee 
分かりました!
基本的にはRails-wayに乗っていてかつコードが読みやすくなるような実装を心がけてみます

**Comment by nyamadori** [comment]
@hashimoto-speee PR 作りました。レビューお願いします!

**Comment by hashimoto-speee** [comment]
@nyamadori 
マージしたらクローズしていいですよ！
では機能追加のIssu立てましょう。
- サムネイル（画像）追加
  仕様についてはIssu内でやりましょう
